//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppRecargarATTFixed.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioConectSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioConect : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarComponentePorFolioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarComponentePorMarcaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarComponentePorNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarComponentePorSucursalOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarTodosUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarSaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarSaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AbonarSaldoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioConect() {
            this.Url = "https://serviciologincomponentemovil.azurewebsites.net/ServicioConect.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GuardarCompletedEventHandler GuardarCompleted;
        
        /// <remarks/>
        public event BuscarComponentePorFolioCompletedEventHandler BuscarComponentePorFolioCompleted;
        
        /// <remarks/>
        public event BuscarComponentePorMarcaCompletedEventHandler BuscarComponentePorMarcaCompleted;
        
        /// <remarks/>
        public event BuscarComponentePorNombreCompletedEventHandler BuscarComponentePorNombreCompleted;
        
        /// <remarks/>
        public event BuscarComponentePorSucursalCompletedEventHandler BuscarComponentePorSucursalCompleted;
        
        /// <remarks/>
        public event SignUpCompletedEventHandler SignUpCompleted;
        
        /// <remarks/>
        public event BuscarTodosUsuariosCompletedEventHandler BuscarTodosUsuariosCompleted;
        
        /// <remarks/>
        public event RegistrarSaldoCompletedEventHandler RegistrarSaldoCompleted;
        
        /// <remarks/>
        public event VerificarSaldoCompletedEventHandler VerificarSaldoCompleted;
        
        /// <remarks/>
        public event AbonarSaldoCompletedEventHandler AbonarSaldoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Login(string user) {
            object[] results = this.Invoke("Login", new object[] {
                        user});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string user) {
            this.LoginAsync(user, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string user, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        user}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guardar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Guardar(string Componente, string Marca, decimal Precio, int CantidadInv, string Sucursal) {
            object[] results = this.Invoke("Guardar", new object[] {
                        Componente,
                        Marca,
                        Precio,
                        CantidadInv,
                        Sucursal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAsync(string Componente, string Marca, decimal Precio, int CantidadInv, string Sucursal) {
            this.GuardarAsync(Componente, Marca, Precio, CantidadInv, Sucursal, null);
        }
        
        /// <remarks/>
        public void GuardarAsync(string Componente, string Marca, decimal Precio, int CantidadInv, string Sucursal, object userState) {
            if ((this.GuardarOperationCompleted == null)) {
                this.GuardarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarOperationCompleted);
            }
            this.InvokeAsync("Guardar", new object[] {
                        Componente,
                        Marca,
                        Precio,
                        CantidadInv,
                        Sucursal}, this.GuardarOperationCompleted, userState);
        }
        
        private void OnGuardarOperationCompleted(object arg) {
            if ((this.GuardarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarCompleted(this, new GuardarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarComponentePorFolio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarComponentePorFolio(int folio) {
            object[] results = this.Invoke("BuscarComponentePorFolio", new object[] {
                        folio});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarComponentePorFolioAsync(int folio) {
            this.BuscarComponentePorFolioAsync(folio, null);
        }
        
        /// <remarks/>
        public void BuscarComponentePorFolioAsync(int folio, object userState) {
            if ((this.BuscarComponentePorFolioOperationCompleted == null)) {
                this.BuscarComponentePorFolioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarComponentePorFolioOperationCompleted);
            }
            this.InvokeAsync("BuscarComponentePorFolio", new object[] {
                        folio}, this.BuscarComponentePorFolioOperationCompleted, userState);
        }
        
        private void OnBuscarComponentePorFolioOperationCompleted(object arg) {
            if ((this.BuscarComponentePorFolioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarComponentePorFolioCompleted(this, new BuscarComponentePorFolioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarComponentePorMarca", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarComponentePorMarca(string Marca) {
            object[] results = this.Invoke("BuscarComponentePorMarca", new object[] {
                        Marca});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarComponentePorMarcaAsync(string Marca) {
            this.BuscarComponentePorMarcaAsync(Marca, null);
        }
        
        /// <remarks/>
        public void BuscarComponentePorMarcaAsync(string Marca, object userState) {
            if ((this.BuscarComponentePorMarcaOperationCompleted == null)) {
                this.BuscarComponentePorMarcaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarComponentePorMarcaOperationCompleted);
            }
            this.InvokeAsync("BuscarComponentePorMarca", new object[] {
                        Marca}, this.BuscarComponentePorMarcaOperationCompleted, userState);
        }
        
        private void OnBuscarComponentePorMarcaOperationCompleted(object arg) {
            if ((this.BuscarComponentePorMarcaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarComponentePorMarcaCompleted(this, new BuscarComponentePorMarcaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarComponentePorNombre", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarComponentePorNombre(string Nombre) {
            object[] results = this.Invoke("BuscarComponentePorNombre", new object[] {
                        Nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarComponentePorNombreAsync(string Nombre) {
            this.BuscarComponentePorNombreAsync(Nombre, null);
        }
        
        /// <remarks/>
        public void BuscarComponentePorNombreAsync(string Nombre, object userState) {
            if ((this.BuscarComponentePorNombreOperationCompleted == null)) {
                this.BuscarComponentePorNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarComponentePorNombreOperationCompleted);
            }
            this.InvokeAsync("BuscarComponentePorNombre", new object[] {
                        Nombre}, this.BuscarComponentePorNombreOperationCompleted, userState);
        }
        
        private void OnBuscarComponentePorNombreOperationCompleted(object arg) {
            if ((this.BuscarComponentePorNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarComponentePorNombreCompleted(this, new BuscarComponentePorNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarComponentePorSucursal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarComponentePorSucursal(string Sucursal) {
            object[] results = this.Invoke("BuscarComponentePorSucursal", new object[] {
                        Sucursal});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarComponentePorSucursalAsync(string Sucursal) {
            this.BuscarComponentePorSucursalAsync(Sucursal, null);
        }
        
        /// <remarks/>
        public void BuscarComponentePorSucursalAsync(string Sucursal, object userState) {
            if ((this.BuscarComponentePorSucursalOperationCompleted == null)) {
                this.BuscarComponentePorSucursalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarComponentePorSucursalOperationCompleted);
            }
            this.InvokeAsync("BuscarComponentePorSucursal", new object[] {
                        Sucursal}, this.BuscarComponentePorSucursalOperationCompleted, userState);
        }
        
        private void OnBuscarComponentePorSucursalOperationCompleted(object arg) {
            if ((this.BuscarComponentePorSucursalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarComponentePorSucursalCompleted(this, new BuscarComponentePorSucursalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SignUp(string usuario, string password) {
            object[] results = this.Invoke("SignUp", new object[] {
                        usuario,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SignUpAsync(string usuario, string password) {
            this.SignUpAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void SignUpAsync(string usuario, string password, object userState) {
            if ((this.SignUpOperationCompleted == null)) {
                this.SignUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignUpOperationCompleted);
            }
            this.InvokeAsync("SignUp", new object[] {
                        usuario,
                        password}, this.SignUpOperationCompleted, userState);
        }
        
        private void OnSignUpOperationCompleted(object arg) {
            if ((this.SignUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignUpCompleted(this, new SignUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarTodosUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BuscarTodosUsuarios() {
            object[] results = this.Invoke("BuscarTodosUsuarios", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarTodosUsuariosAsync() {
            this.BuscarTodosUsuariosAsync(null);
        }
        
        /// <remarks/>
        public void BuscarTodosUsuariosAsync(object userState) {
            if ((this.BuscarTodosUsuariosOperationCompleted == null)) {
                this.BuscarTodosUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarTodosUsuariosOperationCompleted);
            }
            this.InvokeAsync("BuscarTodosUsuarios", new object[0], this.BuscarTodosUsuariosOperationCompleted, userState);
        }
        
        private void OnBuscarTodosUsuariosOperationCompleted(object arg) {
            if ((this.BuscarTodosUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarTodosUsuariosCompleted(this, new BuscarTodosUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarSaldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegistrarSaldo(string Numero, decimal Saldo) {
            object[] results = this.Invoke("RegistrarSaldo", new object[] {
                        Numero,
                        Saldo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarSaldoAsync(string Numero, decimal Saldo) {
            this.RegistrarSaldoAsync(Numero, Saldo, null);
        }
        
        /// <remarks/>
        public void RegistrarSaldoAsync(string Numero, decimal Saldo, object userState) {
            if ((this.RegistrarSaldoOperationCompleted == null)) {
                this.RegistrarSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarSaldoOperationCompleted);
            }
            this.InvokeAsync("RegistrarSaldo", new object[] {
                        Numero,
                        Saldo}, this.RegistrarSaldoOperationCompleted, userState);
        }
        
        private void OnRegistrarSaldoOperationCompleted(object arg) {
            if ((this.RegistrarSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarSaldoCompleted(this, new RegistrarSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarSaldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet VerificarSaldo(string Numero) {
            object[] results = this.Invoke("VerificarSaldo", new object[] {
                        Numero});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarSaldoAsync(string Numero) {
            this.VerificarSaldoAsync(Numero, null);
        }
        
        /// <remarks/>
        public void VerificarSaldoAsync(string Numero, object userState) {
            if ((this.VerificarSaldoOperationCompleted == null)) {
                this.VerificarSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarSaldoOperationCompleted);
            }
            this.InvokeAsync("VerificarSaldo", new object[] {
                        Numero}, this.VerificarSaldoOperationCompleted, userState);
        }
        
        private void OnVerificarSaldoOperationCompleted(object arg) {
            if ((this.VerificarSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarSaldoCompleted(this, new VerificarSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AbonarSaldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AbonarSaldo(decimal Saldo, string NumTelefono) {
            object[] results = this.Invoke("AbonarSaldo", new object[] {
                        Saldo,
                        NumTelefono});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AbonarSaldoAsync(decimal Saldo, string NumTelefono) {
            this.AbonarSaldoAsync(Saldo, NumTelefono, null);
        }
        
        /// <remarks/>
        public void AbonarSaldoAsync(decimal Saldo, string NumTelefono, object userState) {
            if ((this.AbonarSaldoOperationCompleted == null)) {
                this.AbonarSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAbonarSaldoOperationCompleted);
            }
            this.InvokeAsync("AbonarSaldo", new object[] {
                        Saldo,
                        NumTelefono}, this.AbonarSaldoOperationCompleted, userState);
        }
        
        private void OnAbonarSaldoOperationCompleted(object arg) {
            if ((this.AbonarSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AbonarSaldoCompleted(this, new AbonarSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GuardarCompletedEventHandler(object sender, GuardarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarComponentePorFolioCompletedEventHandler(object sender, BuscarComponentePorFolioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarComponentePorFolioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarComponentePorFolioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarComponentePorMarcaCompletedEventHandler(object sender, BuscarComponentePorMarcaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarComponentePorMarcaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarComponentePorMarcaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarComponentePorNombreCompletedEventHandler(object sender, BuscarComponentePorNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarComponentePorNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarComponentePorNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarComponentePorSucursalCompletedEventHandler(object sender, BuscarComponentePorSucursalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarComponentePorSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarComponentePorSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SignUpCompletedEventHandler(object sender, SignUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarTodosUsuariosCompletedEventHandler(object sender, BuscarTodosUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarTodosUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarTodosUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RegistrarSaldoCompletedEventHandler(object sender, RegistrarSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void VerificarSaldoCompletedEventHandler(object sender, VerificarSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AbonarSaldoCompletedEventHandler(object sender, AbonarSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonarSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AbonarSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591